INSERT INTO players (name, cash) VALUES ("Bank", 1000000000);
INSERT INTO players (name) VALUES ("Player 1");
INSERT INTO players (name) VALUES ("Player 2");

INSERT INTO property (name) VALUES ("Collect Your Rent");
INSERT INTO property (name, price, payout) VALUES ("Silver Ridge Ave", 100, 20);
INSERT INTO property (name, price, payout) VALUES ("Hollywood Bowl", 120, 24);
INSERT INTO property (name, price, payout) VALUES ("Glendower Avenue", 140, 28);
INSERT INTO property (name, price, payout) VALUES ("Route 66", 160, 32);
INSERT INTO property (name, price, payout) VALUES ("San Pasqual Street", 180, 36);
INSERT INTO property (name, price, payout) VALUES ("Santa Anita Park", 200, 40);
INSERT INTO property (name, price, payout) VALUES ("Madison Avenue", 220, 44);
INSERT INTO property (name, price, payout) VALUES ("Gridlock", 240, 48);
INSERT INTO property (name, price, payout) VALUES ("Louise Avenue", 260, 52);
INSERT INTO property (name, price, payout) VALUES ("Universal Studios", 280, 56);
INSERT INTO property (name, price, payout) VALUES ("Sunswept Drive", 300, 60);
INSERT INTO property (name, price, payout) VALUES ("Getty Center", 320, 64);
INSERT INTO property (name, price, payout) VALUES ("Dell Avenue", 340, 68);
INSERT INTO property (name, price, payout) VALUES ("Santa Monica Pier", 360, 72);
INSERT INTO property (name, price, payout) VALUES ("Murphy Way", 380, 76);